# $NetBSD: Makefile,v 1.1 2009/02/10 13:43:54 pooka Exp $

.include <bsd.own.mk>

AUTHLOGDBASE= 	/usr/src/local/devel/authlogd

TESTSDIR=	${AUTHLOGDBASE}/tests

TESTS_C=	t_authlog

.include <bsd.test.mk>
